baseURL = "https://ptrteixeira.github.io/me/"
languageCode = "en-us"
title = "Peter Teixeira"
theme = "hugo-coder"

[markup.goldmark.renderer]
unsafe = false

[params]
author = "Peter Teixeira"
description = "Random Thoughts"
avatarurl = "/images/avatar.jpg"
info = "Occasionally writes about things"
hideCredits = false
hideCopyright = true

[[params.social]]
name = "GitHub"
icon = "fa fa-github"
weight = 1
url = "https://github.com/PtrTeixeira"
[[params.social]]
name = "Strava"
icon = "fa fa-bicycle"
weight = 2
url = "https://www.strava.com/athletes/23454143"
[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin"
weight = 3
url = "https://www.linkedin.com/in/PtrTeixeira"
[[params.social]]
name = "Twitter"
icon = "fa fa-twitter"
weight = 4
url = "https://www.twitter.com/PeterTeixeira9"

[languages]
  [languages.en]
    languagename = "English"

    [[languages.en.menu.main]]
    name = "Uses"
    weight = 1
    url = "uses/"

    [[languages.en.menu.main]]
    name = "About"
    weight = 2
    url = "about/"

    [[languages.en.menu.main]]
    name = "Posts"
    weight = 3
    url = "posts/"
