version: 2.1
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.55.6
    steps:
      - checkout
      - run: 
          name: "Create deployment worktree"
          command: git worktree add -B gh-pages public origin/gh-pages
      - run:
          name: "Build site"
          command: HUGO_ENV=production hugo -v
      - run: 
          name: "Test website"
          command: htmlproofer src/public --allow-hash-href --check-html --empty-alt-ignore --disable-external
